export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Services } from "./Services";
export { default as Mission } from "./Mission";
export { default as Visit } from "./Visit";
export { default as WhyChooseUs } from "./WhyChooseUs";
